---
- name: restart zookeeper
  run_once: true
  service:
    name: zookeeper
    state: restarted

- name: restart kafka
  run_once: true
  service:
    name: kafka
    state: restarted

- name: restart schema registry
  run_once: true
  service:
    name: schema-registry
    state: restarted
