---
- name: create zookeeper data directory
  sudo: true
  file:
    state: directory
    dest: "/var/lib/zookeeper/"
    mode: 0755
    owner: root
    group: root

- name: create myid file for zookeeper
  sudo: true
  copy:
    content: "{{ zookeeper_myid }}"
    dest: "/var/lib/zookeeper/myid"
    mode: 0755
    owner: root
    group: root

- name: create /etc/kafka directory
  sudo: true
  file:
    path: /etc/kafka
    state: directory
    mode: 0755
    owner: root
    group: root

- name: configure zookeeper
  sudo: true
  template:
    src: zookeeper.properties.j2
    dest: /etc/kafka/zookeeper.properties
    mode: 0755
    owner: root
    group: root
  notify: restart zookeeper

- name: configure kafka
  sudo: true
  template:
    src: kafka.properties.j2
    dest: /etc/kafka/kafka.properties
    mode: 0755
    owner: root
    group: root
  notify: restart kafka

- name: add zookeeper-runner
  sudo: true
  template:
    src: zookeeper-runner.j2
    dest: /usr/bin/zookeeper-runner
    mode: 0755
    owner: root
    group: root
  notify: restart zookeeper

- name: add kafka-runner
  sudo: true
  template:
    src: kafka-runner.j2
    dest: /usr/bin/kafka-runner
    mode: 0755
    owner: root
    group: root
  notify: restart kafka

- name: add zookeeper service
  sudo: true
  template:
    src: zookeeper.conf.j2
    dest: /etc/init/zookeeper.conf
    mode: 0755
    owner: root
    group: root
  notify: restart zookeeper

- name: add kafka service
  sudo: true
  template:
    src: kafka.conf.j2
    dest: /etc/init/kafka.conf
    mode: 0755
    owner: root
    group: root
  notify: restart kafka
